version: '3'

services:
  nestjs:
    image: stockcraft_nestjs_prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - '8080:8080'
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
