# https://nodejs.org/ko/docs/guides/nodejs-docker-webapp/

FROM node:14.17.6-alpine

WORKDIR /usr/proj/server

COPY package*.json ./

RUN npm install

COPY ./ ./

RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start:prod"]
